[tool.poetry]
name = "bundesnetzagentur-automation"
version = "0.1.0"
description = ""
authors = ["Patrick Stöckle <patrick.stoeckle@posteo.de>"]
license = "GPL-3.0-or-later"
readme = "README.md"
packages = [{ include = "bundesnetzagentur_automation" }]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
helium = "^3.2.6"
typer = "^0.9.0"
jsonschema = "^4.19.2"


[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
black = "^23.12.1"
isort = "^5.13.2"
types-jsonschema = "^4.20.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
bundesnetzagentur-automation = 'bundesnetzagentur_automation:app'
