[tool.poetry]
name = "bundesnetzagentur-automation"
version = "0.1.0"
description = ""
authors = ["Patrick Stöckle <patrick.stoeckle@posteo.de>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "my_package" }]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
helium = "^3.2.6"
typer = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
